### ISSUE TITLE
Network request failed

### ISSUE THREAD

**Issue by iwoork** [bartonhammond/snowflake#163]
Trying the remote heroku parse server on a vanilla install but I get "Network request failed" when trying to sign up for an account. anything I'm missing here?

**Comment by bartonhammond** [comment]
I'm sorry - it appears that Heroku has an error starting the dyno.  Not sure why.

**Comment by iSamuelBarney** [comment]
I had that same issue with the default heroku url include. You might want to make your own or build a local one no issues with those.

**Comment by wookiem** [comment]
@bartonhammond You may want to check that the Heroku environment variable "verbose" is set to true so that you get the detailed server logs.  Also, I notice that the package.json start script hard-codes the environment variables via the setenv file.  I think you may want to drop this so that it is picking up Heroku's user-entered environment variable settings.

**Comment by bartonhammond** [comment]
Yeah. I got a note from Heroku support about the env vars.

Thanks for looking at it.

**Comment by bartonhammond** [comment]
This is fixed now, please verify.

**Comment by iwoork** [comment]
It's still happening... I've ran a heroku instance at https://meetdine.herokuapp.com/parse. Server seems to be working fine. The IOS app itself throws a network request failed even if i used the same credentials that I've setup on heroku.

**Comment by bartonhammond** [comment]
Have you tried debugging?  What did you see?  Are you using https as the
protocol?  Did you try both Anroid and iOS?  I know that iOS requires https.
